node('docker') {
   stage('clone dockerfile') {
    git 'https://github.com/ABBANAPURI0445/docker-ursi.git'
}
  stage('build docker image'){
      sh label: '', script: 'docker image build -t gol:1.0 .'
  }
  stage('Push to DockerHub'){
      sh label: '', script: 'docker login -u abbanapuri0445 -p 9989435354a'
      sh label: '', script: '''docker tag gol:1.0 abbanapuri0445/ursi:1.0
docker push abbanapuri0445/ursi:1.0''' 
  }
  //stage('docker run'){
  //    sh label: '', script: 'docker container run -d -p 80:8080 abbanapuri0445/ursi:1.0'
 // }
} 
