--- 
- hosts: ubuntu 
  become: yes
  tasks:
  - name: install apache2 on ubuntu 
    apt:
      name: apache2 
      state: present 
      update_cache: yes 
- hosts: RHEL  
  become: yes
  tasks: 
  - name: install httpd 
    yum: 
      name: httpd
      state: present 
  - name: start httpd service 
    service: 
      name: httpd
      state: started