- hosts: all
  become: yes
  tasks:
  - name: deploy application
    get_url:
      url: http://jfrog-gameoflife.war
      dest: /var/lib/tomcat8/webapps
      url_username: admin
      url_password: password
    notify: restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: tomcat8
      state: restarted